import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to the Anime Browser</h1>

        <p className={styles.description}>
          Get started by clicking{' '}
          <Link href="/anime">
            <span className="link">here</span>
          </Link>
        </p>
      </main>
    </div>
  )
}

export default Home
